baseurl = "https://scottschlangen.com"
title = "Scott Schlangen"
theme = "hugo-coder-forked"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

enableGitInfo = true
enableRobotsTXT = true

# Hugo settings
[sitemap]
changefreq = 'weekly'
filename = 'sitemap.xml'
priority = 0.5

[params]
author = "Scott Schlangen"
info = ["Cybersecurity Administrator", "City of Carmel, IN"]
description = "Scott Schlangen's personal page - Cybersecurity professional specializing in threat analysis, incident response, identity and access management, and compliance"
keywords = "cybersecurity,threat analysis,incident response,identity management,compliance,cloud security,infosec,soc,security operations,microsoft security"
gravatar = "sschlangen@gmail.com"

faviconSVG = "/img/favicon.svg"
favicon_32 = "/img/favicon.png"

since = 2012
enableTwemoji = true
colorScheme = "auto"
hidecolorschemetoggle = false
# Git Commit in Footer, uncomment the line below to enable it
#commit = "https://github.com/kksudo/kazakov.xyz/tree/"
powered_by = false
# Series see also post count
maxSeeAlsoItems = 5

[taxonomies]
#tag = "tags"
#author = "authors"

# Social links
[[params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 1
url = "https://github.com/schlangens"
target = "_blank"
[[params.social]]
name = "Linkedin"
icon = "fa fa-linkedin fa-2x"
weight = 2
url = "https://www.linkedin.com/in/scottschlangen/"
target = "_blank"
[[params.social]]
name = "scott@scottschlangen.com"
icon = "fa fa-envelope fa-2x"
weight = 3
url = "mailto:scott@scottschlangen.com"
target = "_blank"


# Menu links
[[languages.en.menu.main]]
name = "Home"
weight = 1
url  = "/"
[[languages.en.menu.main]]
name = "About"
weight = 2
url = "about/"
[[languages.en.menu.main]]
name = "Tools & Projects"
weight = 3
url = "tools/"
[[languages.en.menu.main]]
name = "Resume/CV"
weight = 5
url = "cv/"



